version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8-alpine
    container_name: lugx-clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native TCP interface
    environment:
      CLICKHOUSE_DB: lugx_analytics
      CLICKHOUSE_USER: lugx_analytics_user
      CLICKHOUSE_PASSWORD: lugx_analytics_secure
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/init:/docker-entrypoint-initdb.d
    networks:
      - lugx-network
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  clickhouse-client:
    image: clickhouse/clickhouse-client:23.8-alpine
    container_name: lugx-clickhouse-client
    depends_on:
      - clickhouse
    networks:
      - lugx-network
    profiles:
      - tools
    command: --host clickhouse --port 9000

volumes:
  clickhouse_data:

networks:
  lugx-network:
    driver: bridge
