version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: lugx-postgres
    environment:
      POSTGRES_DB: lugx_gaming_db
      POSTGRES_USER: lugx_admin
      POSTGRES_PASSWORD: lugx_secure_password_2025
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    networks:
      - lugx-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lugx_admin -d lugx_gaming_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: lugx-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lugxgaming.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - lugx-network
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  lugx-network:
    driver: bridge
